# Monte Carlo Simulation Configuration File

# Stock tickers to simulate (list of symbols)
tickers:
  - AAPL    # Apple Inc.
  - MSFT    # Microsoft Corporation
  - GOOGL   # Alphabet Inc.

# Simulation parameters
days: 252              # Number of trading days to simulate (1 year = ~252 days)
simulations: 10000     # Number of Monte Carlo simulation paths

# Risk analysis configuration
confidence_levels:
  - 0.95              # 95% confidence level for VaR
  - 0.99              # 99% confidence level for VaR

# Data fetching settings
data:
  period: "1y"                    # Historical data period (1d, 5d, 1mo, 3mo, 6mo, 1y, 2y, 5y, 10y, ytd, max)
  cache_duration_days: 1          # Cache validity in days
  use_cache: true                 # Enable data caching
  force_refresh: false            # Force refresh of cached data
  
  # Alpha Vantage API configuration
  alpha_vantage_api_key: ""       # Get free API key from https://www.alphavantage.co/support/#api-key
  api_rate_limit_per_minute: 5    # Alpha Vantage free tier: 5 calls per minute
  api_daily_limit: 25             # Alpha Vantage free tier: 25 calls per day

# Output settings
output:
  generate_plots: true          # Create visualization plots
  export_csv: true               # Export results to CSV
  plot_sample_paths: 100         # Number of sample paths to show in plots
  
  # File naming
  results_prefix: ""              # Prefix for output files
  timestamp_suffix: false         # Add timestamp to filenames

# Visualization settings
visualization:
  style: "seaborn-v0_8"          # Matplotlib style
  figure_size:
    width: 12
    height: 8
  dpi: 300                       # Plot resolution
  colors:
    primary: "blue"
    secondary: "red"
    accent: "green"

# Monte Carlo model parameters (optional overrides)
model:
  # If specified, these will override calculated values from historical data
  annual_drift_override: null     # Override annual drift (e.g., 0.08 for 8%)
  annual_volatility_override: null # Override annual volatility (e.g., 0.25 for 25%)
  
  # Random seed for reproducible results (null = random)
  random_seed: 42
  
  # Model type (currently only supports 'geometric_brownian_motion')
  type: "geometric_brownian_motion"

# Performance settings
performance:
  max_paths_in_memory: 50000     # Maximum simulation paths to keep in memory
  chunk_size: 1000               # Process simulations in chunks
  use_numba: true                # Enable Numba JIT compilation if available

# Logging settings
logging:
  level: "INFO"                  # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
# Advanced risk metrics (optional)
risk_metrics:
  calculate_var: true            # Value at Risk
  calculate_cvar: true           # Conditional Value at Risk (Expected Shortfall)
  calculate_maximum_drawdown: false # Maximum drawdown analysis
  
# Stress testing scenarios (optional)
stress_tests:
  enabled: false
  scenarios:
    - name: "market_crash"
      drift_multiplier: -2.0
      volatility_multiplier: 2.0
    - name: "bull_market"
      drift_multiplier: 1.5
      volatility_multiplier: 0.8

# Notification settings (for future enhancement)
notifications:
  enabled: false
  webhook_url: null
  email: null
  
# Resource limits
limits:
  max_simulation_days: 1000      # Maximum simulation period
  max_simulations: 100000        # Maximum number of simulations
  max_tickers: 20                # Maximum number of tickers per run
  memory_limit_gb: 8             # Memory usage limit

# Metadata
metadata:
  version: "1.0"
  created_by: "monte-carlo-simulator"
  description: "Default configuration for Monte Carlo stock price simulation"